#!/usr/bin/env python3
"""
package_firmware.py
Assemble the dist/ tree, per-role ZIPs, and the complete BMCU-DM-PRO-ALL.zip.

Expected inputs:
  dist-stage/<env>/firmware.bin   – collected by the matrix build jobs
  dist/<manifest.json>
  dist/<manifest.csv>
  dist/<SHA256SUMS.txt>

Produces:
  dist/
    README-FIRMWARE.md
    manifest.json            (already generated by build_manifest.py)
    manifest.csv
    SHA256SUMS.txt
    AMS-A/
      BMCU-DM-PRO-AMS-A-010.bin ... BMCU-DM-PRO-AMS-A-090.bin
      SHA256SUMS.txt
    AMS-B/ ...  AMS-C/ ... AMS-D/ ... SOLO/ ... LITE/
  BMCU-DM-PRO-AMS-A.zip
  BMCU-DM-PRO-AMS-B.zip
  ...
  BMCU-DM-PRO-LITE.zip
  BMCU-DM-PRO-ALL.zip

Usage:
  python3 scripts/package_firmware.py \
      --bin-dir  dist-stage \
      --dist-dir dist \
      --zip-dir  .
"""

import argparse
import hashlib
import json
import os
import shutil
import sys
import zipfile

# ── Expected matrix ──────────────────────────────────────────────────────────
ROLES   = ["ams_a", "ams_b", "ams_c", "ams_d", "solo", "lite"]
LENGTHS = ["010", "020", "025", "030", "035", "040", "045", "050",
           "055", "060", "065", "070", "075", "080", "085", "090"]

ROLE_META = {
    "ams_a": {"label": "AMS-A", "dir": "AMS-A", "ams_num": 0},
    "ams_b": {"label": "AMS-B", "dir": "AMS-B", "ams_num": 1},
    "ams_c": {"label": "AMS-C", "dir": "AMS-C", "ams_num": 2},
    "ams_d": {"label": "AMS-D", "dir": "AMS-D", "ams_num": 3},
    "solo":  {"label": "SOLO",  "dir": "SOLO",  "ams_num": 0},
    "lite":  {"label": "LITE",  "dir": "LITE",  "ams_num": 0},
}

LENGTH_MM = {l: int(l) * 10 for l in LENGTHS}


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


# ── README-FIRMWARE.md ───────────────────────────────────────────────────────
README_TEMPLATE = """\
# BMCU 370C DM PRO — Firmware Package

## Target hardware

**Product:** BMCU 370C DM PRO
**Printer:** Bambu Lab A1

This firmware requires the **DM PRO hardware variant** with dual filament
microswitches, an AS5600 magnetic rotary sensor, and a high-torque feeder motor.

Single-microswitch BMCU boards are **not** supported by this firmware family.

---

## Microswitch functions

| Switch | Physical location | Function |
|--------|-------------------|----------|
| Rear / spool-side | Behind the feeder, toward the spool | **Autoload trigger** — inserting filament here starts automatic feeding |
| Front / output-side | Toward the toolhead | **Normal unload completion** — unload stops when this switch clears |

### Loading (autoload)

1. Insert filament from the spool side.
2. Rear/spool-side microswitch activates.
3. Feeder motor begins advancing filament automatically.
4. Front/output-side microswitch activates when filament arrives.
5. Load complete.

### Unloading

1. Printer cuts filament and commands pull-back.
2. Feeder retracts filament.
3. Rear/spool microswitch may change — **this is ignored for unload completion**.
4. Front/output microswitch transitions from present → absent.
5. 50 ms debounce.
6. Motor stops — **unload complete**.

**The firmware does NOT normally retract the full configured distance.**
It should stop earlier when the front/output microswitch clears.
The configured distance is only a maximum/fallback safety limit.

**Safety stops** (if front switch never clears):

- `MAX_DISTANCE` — compiled maximum retract distance reached (the suffix value).
- `TIMEOUT` — 90-second absolute timeout.
- `ENCODER_FAULT` — AS5600 magnetic sensor failure.

There is no hidden 100 mm fixed-distance jam fallback.

---

## Roles

| Role  | AMS bus address | Notes |
|-------|-----------------|-------|
| AMS A | 0               | Primary AMS slot A |
| AMS B | 1               | Primary AMS slot B |
| AMS C | 2               | Primary AMS slot C |
| AMS D | 3               | Primary AMS slot D |
| SOLO  | 0               | Currently protocol-equivalent to AMS A — dedicated build flag reserved for future differentiation |
| LITE  | 0               | Currently protocol-equivalent to AMS A — dedicated build flag reserved for future differentiation |

Select the role that matches the physical AMS slot position of your BMCU unit.

---

## Retract-distance suffix

The three-digit suffix in each filename is the **maximum/fallback retract
distance** — NOT the normal unload distance.

Normal unload is controlled by the front/output microswitch.
The selected distance is only used if the switch never clears (safety fallback).

### Examples

| Filename | Max retract fallback |
|----------|---------------------|
| `BMCU-DM-PRO-AMS-A-010.bin` | 100 mm |
| `BMCU-DM-PRO-AMS-A-050.bin` | 500 mm |
| `BMCU-DM-PRO-AMS-A-090.bin` | 900 mm |

In all three cases, if the front/output microswitch clears at 180 mm, the
motor stops at 180 mm — not at the compiled maximum.

### Full suffix table

| Suffix | Max retract fallback |
|--------|---------------------|
| _010   | 100 mm      |
| _020   | 200 mm      |
| _025   | 250 mm      |
| _030   | 300 mm      |
| _035   | 350 mm      |
| _040   | 400 mm      |
| _045   | 450 mm      |
| _050   | 500 mm      |
| _055   | 550 mm      |
| _060   | 600 mm      |
| _065   | 650 mm      |
| _070   | 700 mm      |
| _075   | 750 mm      |
| _080   | 800 mm      |
| _085   | 850 mm      |
| _090   | 900 mm      |

---

## Firmware file table

{table}

---

*Generated automatically during the GitHub Actions build.
Do not flash a binary to the wrong hardware or the wrong AMS slot.*
"""

TABLE_HEADER = """\
| Filename | Role | AMS # | Max retract fallback |
|----------|------|-------|---------------------|
"""


def build_readme(records: list, dist_dir: str) -> str:
    rows = []
    for r in records:
        mm = r.get("retract_limit_mm") or r.get("retract_mm")
        rows.append(
            f"| `{r['filename']}` | {r['role']} | {r['ams_num']} | {mm} mm |"
        )
    table = TABLE_HEADER + "\n".join(rows)
    content = README_TEMPLATE.format(table=table)
    path = os.path.join(dist_dir, "README-FIRMWARE.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[OK] README-FIRMWARE.md -> {path}")
    return path


def assemble_dist(bin_dir: str, dist_dir: str, records: list) -> None:
    """Copy binaries into dist/<ROLE>/ subdirectories."""
    role_sums: dict[str, list] = {r: [] for r in ROLE_META}

    for rec in records:
        if rec["build_result"] != "SUCCESS":
            print(f"[SKIP] {rec['environment']} — not SUCCESS", file=sys.stderr)
            continue

        role_key = rec["environment"].replace("dm_pro_", "").rsplit("_", 1)[0]
        role_dir  = os.path.join(dist_dir, ROLE_META[role_key]["dir"])
        os.makedirs(role_dir, exist_ok=True)

        src  = os.path.join(bin_dir, rec["environment"], "firmware.bin")
        dest = os.path.join(role_dir, rec["filename"])
        shutil.copy2(src, dest)
        role_sums[role_key].append((rec["sha256"], rec["filename"]))

    # Per-role SHA256SUMS.txt
    for role_key, sums in role_sums.items():
        role_dir = os.path.join(dist_dir, ROLE_META[role_key]["dir"])
        with open(os.path.join(role_dir, "SHA256SUMS.txt"), "w") as f:
            for digest, fname in sums:
                f.write(f"{digest}  {fname}\n")

    print(f"[OK] Binaries assembled in {dist_dir}/")


def build_zips(dist_dir: str, zip_dir: str, records: list) -> list:
    """Build per-role ZIPs, the ALL ZIP, and SHA256SUMS-PACKAGES.txt.
    Returns list of created zip paths."""
    zip_paths = []
    readme_path = os.path.join(dist_dir, "README-FIRMWARE.md")

    for role_key, meta in ROLE_META.items():
        zip_name = f"BMCU-DM-PRO-{meta['label']}.zip"
        zip_path = os.path.join(zip_dir, zip_name)
        role_dir = os.path.join(dist_dir, meta["dir"])

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for fname in sorted(os.listdir(role_dir)):
                zf.write(os.path.join(role_dir, fname), fname)
            if os.path.isfile(readme_path):
                zf.write(readme_path, "README-FIRMWARE.md")

        zip_paths.append(zip_path)
        print(f"[OK] {zip_name}")

    # ALL zip
    all_zip_path = os.path.join(zip_dir, "BMCU-DM-PRO-ALL.zip")
    with zipfile.ZipFile(all_zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, _dirs, files in os.walk(dist_dir):
            for fname in files:
                full = os.path.join(root, fname)
                arcname = os.path.relpath(full, os.path.dirname(dist_dir))
                zf.write(full, arcname)

    zip_paths.append(all_zip_path)
    print(f"[OK] BMCU-DM-PRO-ALL.zip")

    # ── SHA256SUMS-PACKAGES.txt ───────────────────────────────────────────
    # Checksums for all release packages and manifest files.
    package_sums_path = os.path.join(zip_dir, "SHA256SUMS-PACKAGES.txt")
    package_files = zip_paths + [
        os.path.join(dist_dir, "manifest.json"),
        os.path.join(dist_dir, "manifest.csv"),
        os.path.join(dist_dir, "README-FIRMWARE.md"),
    ]
    with open(package_sums_path, "w", encoding="utf-8") as f:
        for p in package_files:
            if os.path.isfile(p):
                digest = sha256_file(p)
                f.write(f"{digest}  {os.path.basename(p)}\n")
    print(f"[OK] SHA256SUMS-PACKAGES.txt -> {package_sums_path}")

    return zip_paths


def main() -> None:
    parser = argparse.ArgumentParser(description="Package DM PRO firmware")
    parser.add_argument("--bin-dir",  required=True,  help="Staging dir with per-env binaries")
    parser.add_argument("--dist-dir", required=True,  help="Output dist/ directory")
    parser.add_argument("--zip-dir",  default=".",    help="Where to write .zip files")
    args = parser.parse_args()

    manifest_path = os.path.join(args.dist_dir, "manifest.json")
    if not os.path.isfile(manifest_path):
        print(f"[FAIL] {manifest_path} not found — run build_manifest.py first",
              file=sys.stderr)
        sys.exit(1)

    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    records = manifest["firmware"]

    build_readme(records, args.dist_dir)
    assemble_dist(args.bin_dir, args.dist_dir, records)
    build_zips(args.dist_dir, args.zip_dir, records)

    successful = sum(1 for r in records if r["build_result"] == "SUCCESS")
    print(f"\n[DONE] {successful}/{len(records)} firmware files packaged.")
    if successful != len(records):
        sys.exit(1)


if __name__ == "__main__":
    main()
